### ISSUE TITLE
ui-icon position absolute interferes with backdrop

### ISSUE THREAD

**Issue by ming-codes** [ming-codes/ember-ui-kit#152]
There is an alternative to using position absolute is to wrap the icon svg with another element.

```html
<div class="ui-icon">
  <div style="width: 0; height: 0; overflow: visible">
    <svg></svg>
  </div>
  <div style="width: 0; height: 0; overflow: visible">
    <svg></svg>
  </div>
</div>
```

The zeroes will take the following elements out of flow.

For scaling, we can use fixed dimension with margin.

```css
.ui-icon [data-icon-scale="0.5"] {
  width: 32px;
  height: 32px;
  margin: 16px;
}
```
